general_settings:
  master_key: "dada-litellm-2024"

model_list:
  - model_name: llama-3.1-8b
    litellm_params:
      model: openai/llama3.1-8b
      api_base: https://api.cerebras.ai/v1
      api_key: csk-vntph9k2emycn85wfh4dkwh2hhdf54nr86vhtwjkp82d3rdn
  - model_name: deepseek-v4-flash
    litellm_params:
      model: openai/deepseek-v4-flash
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
  - model_name: deepseek-v4-pro
    litellm_params:
      model: openai/deepseek-v4-pro
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
  - model_name: kimi-k2.6
    litellm_params:
      model: openai/kimi-k2.6
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
  - model_name: qwen3.6-plus
    litellm_params:
      model: openai/qwen3.6-plus
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
  - model_name: glm-5.1
    litellm_params:
      model: openai/glm-5.1
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
  - model_name: minimax-m2.7
    litellm_params:
      model: openai/minimax-m2.7
      api_base: https://opencode.ai/zen/go/v1
      api_key: sk-GCSPmgjX8nirGIr66PEIOKVJN3WQyNQ5FSidS3UQRhBebczNK9dMMR9n1QhHvLtf
